Draft(don't merge yet): Feature/data visualisation
ClairBerlin/como-ui pull request #32
Opened 2022-06-29 09:10 UTC by ZenVega

Hier eine Vorabversion der neuen Installationsdetails. Diese muss noch durch einige daten ergänzt werden, die erst nächste Woche reinkommen.

2022-06-29 10:26 UTC, ZenVega commented
shadows still missing

2022-07-07 21:18 UTC, uliSchuster requested changes
Running the dashboard locally, I do see several errors in the console, mostly related to opening and closing the sidebar. the sidebar itself appears to be very wide now, covering most of the screen when open (tested using Chrome/Brave).

2022-07-07 21:32 UTC, uliSchuster commented
The changes are live on staging for review.
One thing I noticed is that the chart does not include the date of the day shown (if the single-day tab is selected). Maybe you can add the day as additional item below the hour ticks?

2022-07-07 21:36 UTC, uliSchuster commented
Even though the installation card says "Störung" on the overview, the card in the details view shows the last recorded sensor value and even claims that the air quality is good. The two cards should provide consistent information.

2022-07-11 06:11 UTC, ZenVega commented
> 

Marco removed that "today" button in the visualization and so did I. I guess because the default state is the current time and it's also the last choosable option. Do you you think we should put it in again?: https://www.figma.com/file/MqtSmgOqoJHPuiMyqQ26Ae/Webseite?node-id=2476%3A30314

2022-07-11 06:14 UTC, uliSchuster commented
Well, it's your decision of course. But as a user, I would find it odd to reload the page just to get back to today

2022-07-11 06:46 UTC, ZenVega commented on src/views/Overview.vue
> +          class="lg:max-w-3xl flex w-full gap-6 overflow-scroll lg:flex-wrap"
Hmm, I cannot reproduce this. What browser are you using? Did you try replacing it with overflow-auto and did it solve the problem?

2022-07-11 07:41 UTC, rtzll commented on src/views/Overview.vue
> +          class="lg:max-w-3xl flex w-full gap-6 overflow-scroll lg:flex-wrap"
![2022-07-11 09 39 12](https://user-images.githubusercontent.com/3359485/178213106-28b632d2-1ff5-4756-b875-d7f23f2ec82a.gif)

Using Chrome, visiting https://staging.como-berlin.de/dashboard/1.
When I remove the scroll overflow it disappears. `overflow: auto` also removes it.

2022-07-11 11:51 UTC, ZenVega commented
I fixed all comments except the one concerning the "today button". For that topic, I'd go for the UX-Designer's version. I'll however backcheck with him as soon as he's back and discuss this. Until then I'd say we leave it out. Could you push these changes to staging? Thanks

2022-07-11 20:36 UTC, merged